services:
  python-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: tatiana-dashboard
    ports:
      - "8000:8000"
    volumes:
      - ./python_script/data:/data
    depends_on:
      - bash-monitor

  bash-monitor:
    build: ./bash-monitor
    volumes:
      - ./python_script/data:/data
